[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [
    { access = "read", path = "./images/" },
    { access = "read", path = "./broadcast" },
]
#! contracts = inner lib
# contract-upgradeable = outer lib
remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/', 
'@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/']
gas_reports = ["*"]

[fuzz]
runs = 1000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[invariant]
runs=128
depth=10
fail_on_revert=true #false for open invariants
